### ISSUE TITLE
Support Washing machine, model: WCG370

### ISSUE THREAD

**Issue by luckfamousa** [talsalis/homebridge-miele-hood#2]
After installing the plugin and setup I see this in homebridge logs.

[11/01/2021, 21:24:48] [Miele@Home] Discovered device: id: xxx, name: Washing machine, model: WCG370
[11/01/2021, 21:24:48] [Miele@Home] Skipping unsupported device "Washing machine with type identifier: 1.

**Comment by QuickSander** [comment]
I'm confused. You post this on Miele Ventilation Hood, but your logging shows logging from my recent fork of this repository: https://github.com/QuickSander/homebridge-mieleathome.

Could you repost on https://github.com/QuickSander/homebridge-mieleathome ?
It seems I need to extend the plugin to support your washing machine type WCG370 (It currently only supports my Washer dryer combination).

**Comment by luckfamousa** [comment]
I would but it seems that you have disabled public issue posting at https://github.com/QuickSander/homebridge-mieleathome :-)
That's why I posted it here. Sorry.

**Comment by QuickSander** [comment]
Oeps sorry. Now it is enabled. But regarding your issue, I will start to enable it for your washing machine type (raw_value 1) but will require the capabilities it supports from the Miele swagger page to verify it supports the same as my Washer dryer combination.

**Comment by luckfamousa** [comment]
New issue at https://github.com/QuickSander/homebridge-mieleathome/issues/2 including some response from Miele API.
